name: GitHub Actions Build and Deploy vuepress blog
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        with:
          node-version: "12.x"
        run: |
          npm ci
          npm run build
          cd docs/.vuepress/dist
          echo 'blog.easyinmind.top' > CNAME
          cd -

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: blog # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_CI }}
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Build and Deploy
#       uses: JamesIves/github-pages-deploy-action@4.0.0
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_CI }}
#         BRANCH: gh-page
#         FOLDER: docs/.vuepress/dist
#         BUILD_SCRIPT: npm install && npm run build

# && cd docs/.vuepress/dist && echo 'xugaoyi.com' > CNAME && cd -
